name: Deploy to i17e repository within this same org

on:
  push:
    branches:
      - main
      - develop
      
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (main, develop, or feature)"
        required: false
        default: "main"

jobs:
  Build_Deploy:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.head_commit.message, '[ci-skip]')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Adjust the Node.js version as needed


    - name: Build Angular app
      run: |
            npm i
            npm run build -- --configuration production
            #npm run build -- --configuration production --base-href "/i17e/"

    - name: 404 hack
      run: |
            # echo 'Lets see what we have moko'
            # ls -l --ignore=node_modules
            cp dist/i17e/index.html dist/i17e/404.html

    # - name: Debug dist
    #   run: ls -R dist


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT_TOKEN }}
        external_repository: OpensourceKD/i17e
        publish_branch: main
        publish_dir: ./dist/i17e
