name: Deploy to ng-shell repository within this same org

on:
  push:
    branches:
      - main
      - develop
      - feat/*
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (main, develop, or feature)"
        required: false
        default: "main"

jobs:
  Build_Deploy:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.head_commit.message, '[ci-skip]')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Adjust the Node.js version as needed


    - name: Build Angular app
      run: |
            npm i
            # ng-shell is the name of other repo where these static assets are deployed
            # npm run build -- --configuration production --base-href "https://opensourcekd.github.io/shell/"
            npm run build -- --configuration production
            #npm run build -- --output-path=dist/angular-poc-shell/browser

    - name: 404 hack
      run: |
            # echo 'Lets see what we have moko'
            # ls -l --ignore=node_modules
            cp dist/shell/index.html dist/shell/404.html

    # - name: Debug dist
    #   run: ls -R dist


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT_TOKEN }}
        external_repository: OpensourceKD/shell
        publish_branch: main
        publish_dir: ./dist/shell


    # - name: Build and Deploy Shell App
    #   run: |
    #     npm install  # If you're using a build tool like npm
    #     npm run build  # If your project requires a build step
    #     echo 'check root folder'
    #     ls -l
    #     echo 'check dist folder'
    #     cd dist
    #     ls -l

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     personal_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist/angular-poc-shell/browser  # Deploy only the contents of the 'build' directory
    #     external_repository: OpensourceKD/ng-shell
        

    # - name: Deploy to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@4.1.4
    #   with:
    #     token: ${{ secrets.GH_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
